select
    unique_key                                      as request_id,
    {{ ny_parts('created_at', 'created') }},
    created_at,
    closed_at,
    {{ ny('closed_at') }}                           as closed_at_local,
    case when closed_at >= created_at
         then round(epoch(closed_at - created_at) / 3600.0, 2) end as hours_to_close,
    status,
    status = 'Closed'                               as is_closed,
    agency,
    agency_name,
    complaint_type,
    descriptor,
    descriptor_2,
    location_type,
    channel,
    resolution_description,
    borough,
    boro_code,
    nta_code,
    community_district,
    council_district,
    police_precinct,
    taxi_zone_id,
    incident_zip,
    modzcta,
    incident_address,
    street_name,
    latitude,
    longitude
from {{ source('silver', 'requests_311') }}
