select
    collision_id,
    {{ ny_parts('crashed_at', 'crash') }},
    crashed_at,
    persons_injured,
    persons_killed,
    pedestrians_injured,
    pedestrians_killed,
    cyclists_injured,
    cyclists_killed,
    motorists_injured,
    motorists_killed,
    persons_injured > 0                             as has_injury,
    persons_killed > 0                              as has_fatality,
    pedestrians_injured + pedestrians_killed > 0    as involves_pedestrian_harm,
    cyclists_injured + cyclists_killed > 0          as involves_cyclist_harm,
    contributing_factor_1                           as primary_factor,
    contributing_factor_2,
    vehicle_type_1,
    vehicle_type_2,
    on_street_name,
    cross_street_name,
    coalesce(borough, case boro_code when 1 then 'Manhattan' when 2 then 'Bronx'
        when 3 then 'Brooklyn' when 4 then 'Queens' when 5 then 'Staten Island' end) as borough,
    boro_code,
    nta_code,
    community_district,
    council_district,
    police_precinct,
    taxi_zone_id,
    zip_code,
    latitude,
    longitude
from {{ source('silver', 'collision_crashes') }}
